# src/msp_program2.py
# ============================================================
# Program 2: Update RETENTIONTIME in MSP using predicted RT CSV
# Based on MSP_updated.ipynb Program 2.
# ============================================================

from pathlib import Path
import pandas as pd


def read_msp_file(msp_file_path, encoding="utf-8"):
    """
    Read MSP file and split entries by blank line.
    """
    msp_file_path = Path(msp_file_path)
    try:
        content = msp_file_path.read_text(encoding=encoding)
    except UnicodeDecodeError:
        content = msp_file_path.read_text(encoding="latin-1")

    return content.strip().split("\n\n")


def parse_msp_entries_without_new_id(msp_entries):
    """
    Parse MSP entries while preserving existing ID.
    """
    compound_info_list = []

    for entry in msp_entries:
        lines = entry.strip().split("\n")
        compound_info = {}

        for line in lines:
            if ":" in line:
                if ": " in line:
                    key, value = line.split(": ", 1)
                else:
                    key, value = line.split(":", 1)
                    value = value.strip()
                compound_info[key] = value
            else:
                values = line.split("\t")
                if len(values) == 2:
                    mass, abundance = values
                    compound_info[mass] = abundance

        compound_info_list.append(compound_info)

    return compound_info_list


def read_rt_table(updated_rt_csv_path):
    """
    Read RT table.

    Matching ID column:
    - NO, preferred original logic
    - ID, compatible with RT prediction output

    RT column:
    - RT, preferred original logic
    - RETENTIONTIME
    - Predicted_RT, compatible with current RT prediction app output
    """
    rt_data = pd.read_csv(updated_rt_csv_path, dtype=str)

    if "NO" in rt_data.columns:
        id_column = "NO"
    elif "ID" in rt_data.columns:
        id_column = "ID"
    else:
        raise ValueError("RT CSV must contain 'NO' or 'ID' for matching MSP ID.")

    if "RT" in rt_data.columns:
        rt_column = "RT"
    elif "RETENTIONTIME" in rt_data.columns:
        rt_column = "RETENTIONTIME"
    elif "Predicted_RT" in rt_data.columns:
        rt_column = "Predicted_RT"
    else:
        raise ValueError("RT CSV must contain 'RT', 'RETENTIONTIME', or 'Predicted_RT'.")

    return rt_data, id_column, rt_column


def update_retention_time(compound_info_list, rt_data, id_column, rt_column):
    """
    Update RETENTIONTIME by matching MSP ID and CSV ID.
    RETENTIONTIME is rounded to 2 decimals.
    """
    rt_dict = rt_data.set_index(id_column)[rt_column].to_dict()

    matched_count = 0
    for compound_info in compound_info_list:
        if "ID" in compound_info and compound_info["ID"] in rt_dict:
            rt_value = rt_dict[compound_info["ID"]]
            if pd.notna(rt_value) and str(rt_value).strip() != "":
                compound_info["RETENTIONTIME"] = f"{round(float(rt_value), 2):.2f}"
                matched_count += 1

    return compound_info_list, matched_count


def write_msp_file(compound_info_list, output_file_path):
    """
    Write MSP entries.
    ID is written immediately after NAME.
    Peak lines are written as mass<TAB>abundance.
    """
    output_file_path = Path(output_file_path)
    output_file_path.parent.mkdir(parents=True, exist_ok=True)

    updated_msp_entries = []

    for compound_info in compound_info_list:
        updated_lines = []

        for key, value in compound_info.items():
            if key == "NAME":
                updated_lines.append(f"{key}: {value}")
                if "ID" in compound_info:
                    updated_lines.append(f"ID: {compound_info['ID']}")
            elif key == "Num Peaks":
                updated_lines.append(f"{key}: {value}")
            elif key != "ID":
                if key.isalpha():
                    updated_lines.append(f"{key}: {value}")
                else:
                    updated_lines.append(f"{key}\t{value}")

        updated_msp_entries.append("\n".join(updated_lines))

    output_file_path.write_text("\n\n".join(updated_msp_entries), encoding="utf-8")


def program2_update_msp_retention_time(
    msp_with_id_file,
    updated_rt_csv,
    output_folder=None,
    output_filename=None,
):
    """
    Wrapper for Streamlit app.

    Input:
    1. MSP with ID generated by Program 1
    2. RT prediction CSV, e.g. msp_with_updated_rt.csv or unknown_voting_predictions.csv

    Output:
    1. MSP with updated RETENTIONTIME
    """
    msp_with_id_file = Path(msp_with_id_file)
    updated_rt_csv = Path(updated_rt_csv)

    if output_folder is None:
        output_folder = msp_with_id_file.parent / "RT_updated"
    output_folder = Path(output_folder)
    output_folder.mkdir(parents=True, exist_ok=True)

    if output_filename is None or str(output_filename).strip() == "":
        output_filename = f"{msp_with_id_file.stem.replace('_with_ID', '')}_with_updatedRT{msp_with_id_file.suffix}"

    output_msp_path = output_folder / output_filename

    msp_entries = read_msp_file(msp_with_id_file)
    compound_info_list = parse_msp_entries_without_new_id(msp_entries)

    rt_data, id_column, rt_column = read_rt_table(updated_rt_csv)
    compound_info_list, matched_count = update_retention_time(
        compound_info_list, rt_data, id_column, rt_column
    )

    write_msp_file(compound_info_list, output_msp_path)

    return {
        "output_msp_path": output_msp_path,
        "matched_count": matched_count,
        "entry_count": len(compound_info_list),
        "id_column": id_column,
        "rt_column": rt_column,
    }
